/**
 * AI MISSION INTELLIGENCE TYPES & ENUMS
 */

export const AnomalyType = {
  BATTERY_DRAIN_ANOMALY: 'BATTERY_DRAIN_ANOMALY',
  BATTERY_LOW: 'BATTERY_LOW',
  ROVER_HEALTH_DEGRADATION: 'ROVER_HEALTH_DEGRADATION',
  UNEXPECTED_MOVEMENT: 'UNEXPECTED_MOVEMENT',
  MOVEMENT_FAILURE: 'MOVEMENT_FAILURE',
  OBSTACLE_ENCOUNTER: 'OBSTACLE_ENCOUNTER',
  HAZARD_ENCOUNTER: 'HAZARD_ENCOUNTER',
  WEATHER_DEGRADATION: 'WEATHER_DEGRADATION',
  COMMUNICATION_BLACKOUT: 'COMMUNICATION_BLACKOUT',
  MISSION_STALL: 'MISSION_STALL',
  TASK_EXECUTION_FAILURE: 'TASK_EXECUTION_FAILURE',
  RESOURCE_DEPLETION: 'RESOURCE_DEPLETION',
  SENSOR_INCONSISTENCY: 'SENSOR_INCONSISTENCY',
  PLAN_INFEASIBILITY: 'PLAN_INFEASIBILITY'
};

export const AnomalySeverity = {
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const RiskLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};
