/**
 * AUTONOMOUS DECISION ENGINE TYPES & CONSTANTS
 */

export const ActionType = {
  START_TASK: 'START_TASK',
  CONTINUE_TASK: 'CONTINUE_TASK',
  MOVE_ROVER: 'MOVE_ROVER',
  SCAN_TERRAIN: 'SCAN_TERRAIN',
  DETECT_SAMPLE: 'DETECT_SAMPLE',
  COLLECT_SAMPLE: 'COLLECT_SAMPLE',
  VERIFY_SAMPLE: 'VERIFY_SAMPLE',
  RETURN_TO_BASE: 'RETURN_TO_BASE',
  WAIT: 'WAIT',
  PAUSE_MISSION: 'PAUSE_MISSION',
  ABORT_MISSION: 'ABORT_MISSION',
  SEND_STATUS_REPORT: 'SEND_STATUS_REPORT',
  REQUEST_EARTH_GUIDANCE: 'REQUEST_EARTH_GUIDANCE'
};

export const RulePriority = {
  SAFETY_EMERGENCY: 100,
  HAZARD_SAFETY: 80,
  MISSION_OBJECTIVE: 50,
  AUTONOMY_PROGRESS: 30
};
