export const CommandTypes = {
  MOVE_TO: 'MOVE_TO',
  SET_SPEED: 'SET_SPEED',
  DRILL_SAMPLE: 'DRILL_SAMPLE',
  ANALYZE_ATMOSPHERE: 'ANALYZE_ATMOSPHERE',
  ENTER_SAFE_MODE: 'ENTER_SAFE_MODE',
  REBOOT_SUBSYSTEM: 'REBOOT_SUBSYSTEM',
  OPTIMIZE_SOLAR_PANELS: 'OPTIMIZE_SOLAR_PANELS'
};

export const CommandStatus = {
  QUEUED_EARTH: 'QUEUED_EARTH',
  TRANSMITTING: 'TRANSMITTING',
  RECEIVED_ROVER: 'RECEIVED_ROVER',
  EXECUTING: 'EXECUTING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};
