/**
 * MARS MISSION TYPES & CONSTANTS
 */

export const MissionStatus = {
  CREATED: 'CREATED',
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  PAUSED: 'PAUSED',
  WAITING: 'WAITING',
  DEGRADED: 'DEGRADED',
  ABORTING: 'ABORTING',
  ABORTED: 'ABORTED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

export const TaskStatus = {
  PENDING: 'PENDING',
  READY: 'READY',
  IN_PROGRESS: 'IN_PROGRESS',
  BLOCKED: 'BLOCKED',
  WAITING: 'WAITING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const TaskPriority = {
  CRITICAL: 4,
  HIGH: 3,
  NORMAL: 2,
  LOW: 1
};

export const MissionEvent = {
  MISSION_CREATED: 'MISSION_CREATED',
  MISSION_PLANNED: 'MISSION_PLANNED',
  MISSION_STARTED: 'MISSION_STARTED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_FAILED: 'TASK_FAILED',
  TASK_BLOCKED: 'TASK_BLOCKED',
  MISSION_PAUSED: 'MISSION_PAUSED',
  MISSION_RESUMED: 'MISSION_RESUMED',
  MISSION_DEGRADED: 'MISSION_DEGRADED',
  MISSION_ABORTING: 'MISSION_ABORTING',
  MISSION_ABORTED: 'MISSION_ABORTED',
  MISSION_COMPLETED: 'MISSION_COMPLETED',
  MISSION_FAILED: 'MISSION_FAILED'
};

export const MissionCommandType = {
  CREATE_MISSION: 'CREATE_MISSION',
  START_MISSION: 'START_MISSION',
  PAUSE_MISSION: 'PAUSE_MISSION',
  RESUME_MISSION: 'RESUME_MISSION',
  ABORT_MISSION: 'ABORT_MISSION',
  UPDATE_OBJECTIVE: 'UPDATE_OBJECTIVE'
};
