/**
 * AUTONOMOUS MISSION PLANNER TYPES & ENUMS
 */

export const PlanState = {
  PLANNED: 'PLANNED',
  VALIDATED: 'VALIDATED',
  EXECUTING: 'EXECUTING',
  PAUSED: 'PAUSED',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const PlanActionState = {
  PENDING: 'PENDING',
  READY: 'READY',
  EXECUTING: 'EXECUTING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
  BLOCKED: 'BLOCKED'
};

export const PlanRiskLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};
